---
Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
      - gem: beaker-testmode_switcher
        version: '~> 0.4'
      - gem: master_manipulator
      - gem: puppet-blacksmith
        version: '~> 3.4'

# For the moment don't do any rubocop checks.
.rubocop.yml:
  include_todos: true
  selected_profile: off

spec/default_facts.yml:
  unmanaged: true

# Due to https://github.com/puppetlabs/pdk-templates/issues/133 we can't manage Travis CI yet.
.travis.yml:
  unmanaged: true

# Due to https://github.com/puppetlabs/pdk-templates/issues/229 we can't manage Appveyor yet.
appveyor.yml:
  unmanaged: true

.gitlab-ci.yml:
  delete: true
